//this file has been generated by rollup-ns
//#region ComplexBaseClass.ts
namespace Samples.Complex
{
import BaseClass = Samples.Basic.BaseClass;

export class ComplexBaseClass extends BaseClass {
}

}
//#endregion ComplexBaseClass.ts
//#region ComplexSubClass.ts
namespace Samples.Complex
{
import SubClass = Samples.Basic.SubFolder.SubClass;

export class ComplexSubClass extends SubClass {
}

}
//#endregion ComplexSubClass.ts
//#region DecrementModule.ts.d
namespace Samples.Complex
{

    export interface ComplexBaseClass {
    /**
             * decrement the base property value
             */
    decrement(): void;
}

}
//#endregion DecrementModule.ts.d
//#region IncrementModule.ts.d
namespace Samples.Complex
{

    export interface ComplexBaseClass {
    /**
         * increment the base property value
         */
    increment(): void;
}

}
//#endregion IncrementModule.ts.d
//#region WindowExtensions.ts
namespace Samples.Complex.Extensions
{


(() => {
    window.baseClass = new ComplexBaseClass()
})()
}
//#endregion WindowExtensions.ts
//#region DecrementModule.ts
namespace Samples.Complex.Modules
{


(() => {
    ComplexBaseClass.prototype.decrement = function (this: ComplexBaseClass) {
        this.baseProp -= 1;
    }
})()
}
//#endregion DecrementModule.ts
//#region IncrementModule.ts
namespace Samples.Complex.Modules
{


(() => {
    ComplexBaseClass.prototype.increment = function (this: ComplexBaseClass) {
        this.baseProp += 1;
    }
})()
}
//#endregion IncrementModule.ts
