//this file has been generated by rollup-ns
//#region ExternalClass.ts
namespace Samples.ExternalPackage
{
import BaseClass = Samples.Basic.BaseClass;

export class ExternalClass extends BaseClass {
    decrement(): void {
        this.baseProp -= 1;
    }
}
}
//#endregion ExternalClass.ts
