//this file has been generated by rollup-ns
export { }
import MyModule = Samples.GlobalAugmentation.MyModule;
declare global {
    export interface Array<T> {
    myModule: MyModule;
    myMethod(): void;
}
}
declare global {
    export interface Window {
        myModule: MyModule;
        myMethod(): void;
    }
}
