//this file has been generated by rollup-ns
//#region MyModule.ts
namespace Samples.GlobalAugmentation
{
export class MyModule {
    member: number;
}

}
//#endregion MyModule.ts
//#region ArrayExtensions.ts
namespace Samples.GlobalAugmentation.Extensions
{


(() => {
    Array.prototype.myModule = window.myModule || new MyModule();
    Array.prototype.myMethod = function (this: Window) {
        console.log('Extension method on window')
    }
})();
}
//#endregion ArrayExtensions.ts
//#region WindowExtensions.ts
namespace Samples.GlobalAugmentation.Extensions
{


(() => {
    console.log('extending window with myModule...')
    window.myModule = window.myModule || new MyModule();
    console.log('extending window with myMethod...')
    window.myMethod = function (this: Window) {
        console.log('Extension method on window')
    }
})();
}
//#endregion WindowExtensions.ts
