var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
//this file has been generated by rollup-ns
//#region EnumType.ts
var Samples;
(function (Samples) {
    var Basic;
    (function (Basic) {
        var EnumType;
        (function (EnumType) {
            EnumType[EnumType["A"] = 0] = "A";
            EnumType[EnumType["B"] = 1] = "B";
            EnumType[EnumType["C"] = 2] = "C";
        })(EnumType = Basic.EnumType || (Basic.EnumType = {}));
    })(Basic = Samples.Basic || (Samples.Basic = {}));
})(Samples || (Samples = {}));
//#endregion EnumType.ts
//#region BaseClass.ts
(function (Samples) {
    var Basic;
    (function (Basic) {
        var BaseClass = /** @class */ (function () {
            function BaseClass() {
                this.baseProp = 0;
                this.enumField = Basic.EnumType.A;
            }
            return BaseClass;
        }());
        Basic.BaseClass = BaseClass;
    })(Basic = Samples.Basic || (Samples.Basic = {}));
})(Samples || (Samples = {}));
//#endregion BaseClass.ts
//#region EnumB.ts
(function (Samples) {
    var Basic;
    (function (Basic) {
        var SubFolder;
        (function (SubFolder) {
            var EnumB;
            (function (EnumB) {
                EnumB[EnumB["X"] = 0] = "X";
                EnumB[EnumB["Y"] = 1] = "Y";
                EnumB[EnumB["Z"] = 2] = "Z";
            })(EnumB = SubFolder.EnumB || (SubFolder.EnumB = {}));
        })(SubFolder = Basic.SubFolder || (Basic.SubFolder = {}));
    })(Basic = Samples.Basic || (Samples.Basic = {}));
})(Samples || (Samples = {}));
//#endregion EnumB.ts
//#region SubClass.ts
(function (Samples) {
    var Basic;
    (function (Basic) {
        var SubFolder;
        (function (SubFolder) {
            var SubClass = /** @class */ (function (_super) {
                __extends(SubClass, _super);
                function SubClass() {
                    return _super !== null && _super.apply(this, arguments) || this;
                }
                return SubClass;
            }(Basic.BaseClass));
            SubFolder.SubClass = SubClass;
        })(SubFolder = Basic.SubFolder || (Basic.SubFolder = {}));
    })(Basic = Samples.Basic || (Samples.Basic = {}));
})(Samples || (Samples = {}));
//#endregion SubClass.ts
