//this file has been generated by rollup-ns
//#region BaseClass.ts
namespace Samples.ScopedAugmentation
{

//example class to augment
export class BaseClass {
    method(): void {
    }
}

}
//#endregion BaseClass.ts
//#region BaseClassExtensionA.ts.d
namespace Samples.ScopedAugmentation
{

    export interface BaseClass {
    extensionB(): void;
}

}
//#endregion BaseClassExtensionA.ts.d
//#region BaseClassExtensionB.ts.d
namespace Samples.ScopedAugmentation
{

    export interface BaseClass {
    extensionB(): void;
}

}
//#endregion BaseClassExtensionB.ts.d
//#region BaseClassExtensionA.ts
namespace Samples.ScopedAugmentation.ExtensionA
{


(() => {
    //extends the base class...
    BaseClass.prototype.extensionB = () => { };
})()

}
//#endregion BaseClassExtensionA.ts
//#region BaseClassExtensionB.ts
namespace Samples.ScopedAugmentation.ExtensionA
{


(() => {
    //extends the base class...
    BaseClass.prototype.extensionB = () => { };
})()

}
//#endregion BaseClassExtensionB.ts
