//this file has been generated by rollup-ns
//#region BaseClass.ts
var Samples;
(function (Samples) {
    var ScopedAugmentation;
    (function (ScopedAugmentation) {
        //example class to augment
        var BaseClass = /** @class */ (function () {
            function BaseClass() {
            }
            BaseClass.prototype.method = function () {
            };
            return BaseClass;
        }());
        ScopedAugmentation.BaseClass = BaseClass;
    })(ScopedAugmentation = Samples.ScopedAugmentation || (Samples.ScopedAugmentation = {}));
})(Samples || (Samples = {}));
//#endregion BaseClassExtensionB.ts.d
//#region BaseClassExtensionA.ts
(function (Samples) {
    var ScopedAugmentation;
    (function (ScopedAugmentation) {
        var ExtensionA;
        (function (ExtensionA) {
            (function () {
                //extends the base class...
                ScopedAugmentation.BaseClass.prototype.extensionB = function () { };
            })();
        })(ExtensionA = ScopedAugmentation.ExtensionA || (ScopedAugmentation.ExtensionA = {}));
    })(ScopedAugmentation = Samples.ScopedAugmentation || (Samples.ScopedAugmentation = {}));
})(Samples || (Samples = {}));
//#endregion BaseClassExtensionA.ts
//#region BaseClassExtensionB.ts
(function (Samples) {
    var ScopedAugmentation;
    (function (ScopedAugmentation) {
        var ExtensionA;
        (function (ExtensionA) {
            (function () {
                //extends the base class...
                ScopedAugmentation.BaseClass.prototype.extensionB = function () { };
            })();
        })(ExtensionA = ScopedAugmentation.ExtensionA || (ScopedAugmentation.ExtensionA = {}));
    })(ScopedAugmentation = Samples.ScopedAugmentation || (Samples.ScopedAugmentation = {}));
})(Samples || (Samples = {}));
//#endregion BaseClassExtensionB.ts
